CREATE DATABASE s203;

USE s203;

CREATE TABLE comment
(
    id INT PRIMARY KEY AUTO_INCREMENT,
    pseudo VARCHAR(30),
    comment TEXT,
    date DATE DEFAULT now()
);

CREATE USER s203 IDENTIFIED BY 's203';
GRANT ALL PRIVILEGES ON *.* TO s203@localhost;
FLUSH PRIVILEGES;